services:
    # node red services
    adadgio_gear.nodered.connector:
        class: Adadgio\GearBundle\NodeRed\NodeRedConnector
        arguments:
            - "%adadgio_gear.nodered%"

    adadgio_gear.nodered.flow_builder:
        class: Adadgio\GearBundle\NodeRed\Configuration\FlowBuilder
        arguments:
            - "@file_locator"
            - "%adadgio_gear.nodered%"

    # core api services
    adadgio_gear.api.core_service:
        class: Adadgio\GearBundle\Component\Api\ApiCoreService
        arguments:
            - "%adadgio_gear.api%"
            - "@=(parameter('adadgio_gear.api.auth.provider')) ? container.get(parameter('adadgio_gear.api.auth.provider')) : null"

    adadgio_gear.api.kernel_event_listener:
        class: Adadgio\GearBundle\Component\Api\Listener\ApiKernelEventListener
        tags:
            - {name: kernel.event_listener, event: kernel.controller, method: onKernelController}
            - {name: kernel.event_listener, event: kernel.exception, method: onKernelException}
        arguments:
            - "@annotation_reader"
            - "@adadgio_gear.api.core_service"

    # authenticator example services
    adadgio_gear.api.authenticator_example_service:
        class: Adadgio\GearBundle\Component\Api\Authenticator\ExampleAuthProviderService
        tags:
            - { name: adadgio_gear.api.authenticator }
        arguments:
            - "@doctrine.orm.entity_manager"

    # entity serialization
    adadgio_gear.entity_serializer:
        class: Adadgio\GearBundle\Component\Serialization\EntitySerializer
        arguments:
            - "%adadgio_gear.serialization%"

    # csv exporter
    adadgio_gear.csv_exporter:
        class: Adadgio\GearBundle\Component\Reader\CsvExporter
        arguments:
            - "@doctrine.orm.entity_manager"
